const data = {
  projects: [
    {
      name: 'Showman Video',
      description:
        'A fullstack web application for delivering on-demand custom videos',
      extra_info: `Showman video is a full-stack web application that Uses a unique combination of technologies to deliver custom & on-demand videos to individuals and businesses.

        It uses React for the front-end, Django for user authentication and page management, and the REST API to communicate with AWS for user renders`,
      tagline: 'The Magnum Opus',
      story: `I’ve been selling my graphics to people online since I was a kid, and it’s always something I’ve been passionate about. 

        Showman is the culmination of all of my ideas since starting my journey into graphics. It is the most challenging, and rewarding project that I’ve worked on. Each time I ran into a problem, I found a solution. 
        
        And I sure did run into a lot of problems. Python was my forte, but to fulfill my dream of creating this, I jumped completely into learning various web technologies from React to AWS. It took trial & error plus my signature night-hawkishness to get this project to where it is.
        
        It uses Blender to render Motion Graphics generated by another project of mine: Rocketeer. It is something I’ve built from the ground up and am pretty proud of. `,

      second_heading: 'Getting Started',
      second_description: `I’ve been selling my graphics to people online since I was a kid, and it’s always something I’ve been passionate about. 

      Showman is the culmination of all of my ideas since starting my journey into graphics. It is the most challenging, and rewarding project that I’ve worked on. Each time I ran into a problem, I found a solution. 
      
      And I sure did run into a lot of problems. Python was my forte, but to fulfill my dream of creating this, I jumped completely into learning various web technologies from React to AWS. It took trial & error plus my signature night-hawkishness to get this project to where it is.
      
      It uses Blender to render Motion Graphics generated by another project of mine: Rocketeer. It is something I’ve built from the ground up and am pretty proud of. `,
      challenges: `My main challenge? The backend. Despite the fact that I started programming by creating python scripts, it was a lot more comfortable creating the frontend. Having this communicate with Blender on a server in order to receive user renders was the hardest part`,
    },
    {
      name: 'Showman Video',
      description:
        'A fullstack web application for delivering on-demand custom videos',
      extra_info: `Showman video is a full-stack web application that Uses a unique combination of technologies to deliver custom & on-demand videos to individuals and businesses.

        It uses React for the front-end, Django for user authentication and page management, and the REST API to communicate with AWS for user renders`,
      tagline: 'The Magnum Opus',
      story: `I’ve been selling my graphics to people online since I was a kid, and it’s always something I’ve been passionate about. 

        Showman is the culmination of all of my ideas since starting my journey into graphics. It is the most challenging, and rewarding project that I’ve worked on. Each time I ran into a problem, I found a solution. 
        
        And I sure did run into a lot of problems. Python was my forte, but to fulfill my dream of creating this, I jumped completely into learning various web technologies from React to AWS. It took trial & error plus my signature night-hawkishness to get this project to where it is.
        
        It uses Blender to render Motion Graphics generated by another project of mine: Rocketeer. It is something I’ve built from the ground up and am pretty proud of. `,

      second_heading: 'Getting Started',
      second_description: `I’ve been selling my graphics to people online since I was a kid, and it’s always something I’ve been passionate about. 

      Showman is the culmination of all of my ideas since starting my journey into graphics. It is the most challenging, and rewarding project that I’ve worked on. Each time I ran into a problem, I found a solution. 
      
      And I sure did run into a lot of problems. Python was my forte, but to fulfill my dream of creating this, I jumped completely into learning various web technologies from React to AWS. It took trial & error plus my signature night-hawkishness to get this project to where it is.
      
      It uses Blender to render Motion Graphics generated by another project of mine: Rocketeer. It is something I’ve built from the ground up and am pretty proud of. `,

      challenges: ``,
    },

    {
      name: 'Showmawn Video',
      description:
        'A fullstack web application for delivering on-demand custom videos',
      extra_info: `Showman video is a full-stack web application that Uses a unique combination of technologies to deliver custom & on-demand videos to individuals and businesses.

        It uses React for the front-end, Django for user authentication and page management, and the REST API to communicate with AWS for user renders`,
      tagline: 'The Magnum Opus',
      story: `I’ve been selling my graphics to people online since I was a kid, and it’s always something I’ve been passionate about. 

        Showman is the culmination of all of my ideas since starting my journey into graphics. It is the most challenging, and rewarding project that I’ve worked on. Each time I ran into a problem, I found a solution. 
        
        And I sure did run into a lot of problems. Python was my forte, but to fulfill my dream of creating this, I jumped completely into learning various web technologies from React to AWS. It took trial & error plus my signature night-hawkishness to get this project to where it is.
        
        It uses Blender to render Motion Graphics generated by another project of mine: Rocketeer. It is something I’ve built from the ground up and am pretty proud of. `,

      second_heading: 'Getting Started',
      second_description: `I’ve been selling my graphics to people online since I was a kid, and it’s always something I’ve been passionate about. 

      Showman is the culmination of all of my ideas since starting my journey into graphics. It is the most challenging, and rewarding project that I’ve worked on. Each time I ran into a problem, I found a solution. 
      
      And I sure did run into a lot of problems. Python was my forte, but to fulfill my dream of creating this, I jumped completely into learning various web technologies from React to AWS. It took trial & error plus my signature night-hawkishness to get this project to where it is.
      
      It uses Blender to render Motion Graphics generated by another project of mine: Rocketeer. It is something I’ve built from the ground up and am pretty proud of. `,

      challenges: ``,
    },
  ],
};

export default data;
